// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IDX_ProductCategory");

                    b.HasIndex("Name")
                        .HasDatabaseName("IDX_ProductName");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 14, 6, 59, 58, 679, DateTimeKind.Utc).AddTicks(7027),
                            Description = "High-performance gaming laptop with RTX 4080",
                            Name = "Laptop",
                            Price = 1500.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 14, 6, 59, 58, 679, DateTimeKind.Utc).AddTicks(7202),
                            Description = "Ergonomic wireless mouse with precision tracking",
                            Name = "Wireless Mouse",
                            Price = 25.00m,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 14, 6, 59, 58, 679, DateTimeKind.Utc).AddTicks(7205),
                            Description = "RGB mechanical keyboard with Cherry MX switches",
                            Name = "Mechanical Keyboard",
                            Price = 100.00m,
                            Quantity = 150
                        },
                        new
                        {
                            Id = 4,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 2, 14, 6, 59, 58, 679, DateTimeKind.Utc).AddTicks(7208),
                            Description = "7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader",
                            Name = "USB-C Hub",
                            Price = 45.00m,
                            Quantity = 300
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 2, 14, 6, 59, 58, 679, DateTimeKind.Utc).AddTicks(7210),
                            Description = "1080p HD webcam with auto-focus",
                            Name = "Webcam HD",
                            Price = 75.00m,
                            Quantity = 120
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
